# Generated by Django 6.0.2 on 2026-03-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='site_name',
            new_name='password_name',
        ),
    ]
