# Generated by Django 6.0.3 on 2026-03-30 02:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0002_rename_site_name_passwordentry_password_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='pin',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='vault_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
