# Generated by Django 6.0.3 on 2026-03-30 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0004_remove_passwordentry_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpin',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
